### ISSUE TITLE
extended support for comma,array fat arrow, etc..

### ISSUE THREAD

**Issue by ctf0** [austenc/blade-spacer#11]
so instead of something like
> @include('post',['row'=>$posts])

or

> {{ Form::open(['route'=>'save.post','files'=>true]) }}

or

> {{ Form::file('photo[]',['multiple'=>true,'class'=>'form-control-file']) }}

the plugin would add a space after each comma,array fat arrow, etc..

**Comment by austenc** [comment]
While this does seem like a good idea, I believe it's outside the scope of this plugin. If you'd like to submit a pull request I'll consider it, but I could see this conflicting with other plugins too, so I won't be implementing this for now.
