### ISSUE TITLE
Vue js Support

### ISSUE THREAD

**Issue by stefanoruth** [austenc/blade-spacer#13]
I know this is ment for Laravel Blade syntax, but i was woundering if you wound consider add support for .vue files becouse those files uses the same syntax with {{ | }}

**Comment by austenc** [comment]
Absolutely @stefanoruth I'll fix this soon. It actually used to work with vue, but I recently restricted the plugin because it was affecting some people with similar syntax plugins. Vue makes a lot of sense to add back. Thanks for letting me know!

**Comment by austenc** [comment]
Thanks for reporting this @stefanoruth, it should work for you now!
