### ISSUE TITLE
Closing brace sometimes missing

### ISSUE THREAD

**Issue by austenc** [austenc/blade-spacer#5]
something like (haven't figured out full scenario, doesn't always work):

```
<h1>This is some text {{ | }</h1>
```

**Comment by KingGeneral** [comment]
+1 for this, 

for me occurrence : because open double separated tab, after that it will be like this,

**Comment by austenc** [comment]
@KingGeneral I appreciate the feedback -- I still haven't nailed down exactly how to reproduce this, but this should help. I'll try to dig in and fix this soon!

**Comment by austenc** [comment]
This line also causes a missing (end) bracket, where `@` represents the cursor position:
`<h2>Skill Test #{{ $skill->id }} <small>for <a href="@"></a></small></h2>`

**Comment by austenc** [comment]
Well, I thought that this was fixed, and it's close, but it needs to also look for surrounding `<` `>` html tags.

**Comment by austenc** [comment]
Even with the test case I described, I can't seem to replicate this. 

If anyone has this occur, please let me know how!
